version: '3'
services:
  server:
    image: node:12.4.0-alpine
    container_name: employes-server
    working_dir: /server
    volumes:
    - ./server:/server
    command: npm install && npm run dev
    ports:
    - "4000:4000"
    networks:
    - aymen
      
networks:
  aymen:
    driver: bridge